version: "3"

volumes:
  psqlDemo:
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ejemplo
    ports:
      - "5432:5432"
    volumes:
      - psqlDemo:/var/lib/psql